
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.ux.BoxReorderer": "../../ext/src/ux/BoxReorderer.js",
  "Ext.ux.CellDragDrop": "../../ext/src/ux/CellDragDrop.js",
  "Ext.ux.SlidingPager": "../../ext/src/ux/SlidingPager.js",
  "Ext.ux.GroupTabRenderer": "../../ext/src/ux/GroupTabRenderer.js",
  "Ext.ux.TabReorderer": "../../ext/src/ux/TabReorderer.js",
  "Ext.ux.upload.uploader.ExtJsUploader": "../../app/view/ux/upload/uploader/LegacyExtJsUploader.js",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "Ext.ux.layout": "../../ext/src/ux/layout",
  "App.controller.WebCam": "../../app/controller/Webcam.js",
  "Ext.ux.FieldReplicator": "../../ext/src/ux/FieldReplicator.js",
  "Ext.ux.RowExpander": "../../ext/src/ux/RowExpander.js",
  "Ext.ux.data": "../../ext/src/ux/data",
  "Ext.ux.form": "../../ext/src/ux/form",
  "Ext": "../../ext/src",
  "Ext.ux": "../../app/view/ux",
  "Ext.ux.ajax": "../../ext/src/ux/ajax",
  "Ext.ux.ToolbarDroppable": "../../ext/src/ux/ToolbarDroppable.js",
  "Ext.ux.event": "../../ext/src/ux/event",
  "App.view.ux.WebCamWindow": "../../app/view/ux/WebcamWindow.js",
  "Ext.ux.GMapPanel": "../../ext/src/ux/GMapPanel.js",
  "ExtThemeNeptune": "../../ext/packages/ext-theme-neptune/overrides",
  "Ext.ux.TabScrollerMenu": "../../ext/src/ux/TabScrollerMenu.js",
  "Ext.ux.IFrame": "../../ext/src/ux/IFrame.js",
  "Ext.ux.TabCloseMenu": "../../ext/src/ux/TabCloseMenu.js",
  "Ext.ux.GroupTabPanel": "../../ext/src/ux/GroupTabPanel.js",
  "Ext.ux.upload.Dialog": "../../app/view/ux/upload/LegacyDialog.js",
  "Ext.ux.LiveSearchGridPanel": "../../ext/src/ux/LiveSearchGridPanel.js",
  "Ext.ux.DataTip": "../../ext/src/ux/DataTip.js",
  "Ext.ux.dd": "../../ext/src/ux/dd",
  "App": "../../app",
  "Ext.ux.TreePicker": "../../ext/src/ux/TreePicker.js",
  "Ext.ux.statusbar": "../../ext/src/ux/statusbar",
  "Ext.ux.PreviewPlugin": "../../ext/src/ux/PreviewPlugin.js",
  "Ext.ux.grid": "../../ext/src/ux/grid",
  "Ext.ux.Spotlight": "../../ext/src/ux/Spotlight.js",
  "Ext.ux.DataView": "../../ext/src/ux/DataView",
  "Extensible.calendar.CalendarPanel": "../../app/view/admin/AppointmentCalendar.js",
  "Ext.ux.ProgressBarPager": "../../ext/src/ux/ProgressBarPager.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "App.view.ux.InsuranceCombo": [],
  "App.view.admin.EmailTemplates": [],
  "App.view.patient.InformacionMedica": [],
  "Ext.ux.upload.Store": [],
  "App.view.admin.IPAccess": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "App.controller.Patient": [],
  "App.view.logon.AdminForm": [],
  "App.model.admin.ConsentLetters": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "App.view.admin.NewAppointmentWindow": [],
  "App.Application": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "App.model.admin.PatientDemographics": [],
  "Ext.ux.DataView.DragSelector": [],
  "App.model.admin.Batches": [],
  "App.view.PatientArea": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.upload.ItemGridPanel": [],
  "Ext.ux.upload.Item": [],
  "App.store.admin.IPAccess": [],
  "App.model.admin.Users": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "App.view.patient.Insurance": [],
  "App.view.ux.ActivityMonitor": [],
  "App.view.admin.ConsentLetterDetails": [],
  "Ext.ux.PreviewPlugin": [],
  "App.view.patient.InsuranceCard": [],
  "App.view.logon.Window": [],
  "App.view.admin.ConsentLetters": [],
  "App.model.admin.Templates": [],
  "App.view.patient.Demographics": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.upload.BrowseButton": [],
  "Ext.ux.upload.uploader.AbstractUploader": [],
  "Ext.ux.ajax.Simlet": [],
  "App.controller.Forms": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "App.store.admin.Templates": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.upload.uploader.DummyUploader": [],
  "App.view.patient.Calendar": [],
  "ExtThemeNeptune.panel.Table": [],
  "Ext.ux.upload.uploader.FormDataUploader": [],
  "App.view.admin.CMS": [],
  "App.view.Viewport": [],
  "Ext.ux.event.Recorder": [],
  "App.controller.Navigation": [],
  "App.view.fields.PatientSearch": [],
  "App.view.admin.AppointmentCalendar": [],
  "App.view.fields.AppointmentBooks": [],
  "App.model.admin.GeoIps": [],
  "App.model.admin.InsuranceCombo": [],
  "App.store.admin.PatientDemographics": [],
  "Ext.ux.ajax.SimManager": [],
  "App.store.admin.AppointmentBooks": [],
  "App.view.admin.Users": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "App.view.admin.Plugins": [],
  "App.view.ux.WebCamWindow": [],
  "App.view.admin.CMSDetails": [],
  "Ext.ux.TabScrollerMenu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [],
  "App.controller.Main": [],
  "App.model.admin.Documents": [],
  "App.model.calendar.PatientSearch": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "App.store.calendar.PatientSearch": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.upload.Panel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "App.view.admin.Reports": [],
  "Ext.ux.TreePicker": [],
  "App.view.patient.ConsentLetters": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "App.store.admin.CMS": [],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "App.model.admin.PatientInsurance": [],
  "App.store.admin.Appointments": [],
  "App.controller.Abstract": [],
  "Ext.ux.upload.uploader.ExtJsUploader": [],
  "Ext.ux.upload.Manager": [],
  "App.model.admin.Referring": [],
  "Ext.ux.FieldReplicator": [],
  "App.model.admin.Sessions": [],
  "App.model.admin.PatientClinical": [],
  "ExtThemeNeptune.panel.Panel": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "App.view.admin.Administrative": [],
  "App.store.admin.ConsentSignatures": [],
  "App.controller.Calendar": [],
  "App.store.admin.PatientInsurance": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "App.model.admin.CMS": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "App.view.ux.RelationsCombo": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.upload.uploader.AbstractXhrUploader": [],
  "App.view.logon.PatientForm": [],
  "App.store.admin.ConsentLetters": [],
  "App.model.admin.Confirmations": [],
  "App.view.fields.DateTime": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "App.controller.Plugins": [],
  "Ext.ux.layout.Center": [],
  "App.view.AdminArea": [],
  "App.store.admin.Users": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "App.store.admin.Logs": [],
  "Ext.ux.upload.data.Connection": [],
  "App.view.Request": [],
  "App.store.WebCamCameras": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "ExtThemeNeptune.layout.component.Dock": [],
  "App.controller.WebCam": [],
  "App.model.admin.Appointments": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "App.view.ux.NavigationTabs": [],
  "Ext.ux.event.Player": [],
  "App.view.admin.AppointmentBooks": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "App.view.ux.StateCombo": [],
  "App.view.ux.SexCombo": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.upload.StatusBar": [],
  "Ext.ux.DataView.Draggable": [],
  "App.model.admin.ConsentSignatures": [],
  "App.store.admin.PatientClinical": [],
  "Ext.ux.TabCloseMenu": [],
  "App.view.admin.Logs": [],
  "Ext.ux.upload.Dialog": [],
  "App.controller.Admin": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "App.model.admin.AppointmentBooks": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "App.view.patient.ThankYou": [],
  "Ext.ux.upload.Queue": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [],
  "ExtThemeNeptune.Component": [],
  "App.model.admin.FacultyCombo": [],
  "App.model.admin.IPAccess": [],
  "App.model.admin.Logs": [],
  "App.model.admin.Plugins": []
});
Ext.ClassManager.addNameAliasMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "App.view.ux.InsuranceCombo": [
    "widget.insurancecombo"
  ],
  "App.view.admin.EmailTemplates": [
    "widget.emailtemplates"
  ],
  "App.view.patient.InformacionMedica": [
    "widget.medicalhistory"
  ],
  "Ext.ux.upload.Store": [],
  "App.view.admin.IPAccess": [
    "widget.ipaccess"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "App.controller.Patient": [],
  "App.view.logon.AdminForm": [
    "widget.logonadminform"
  ],
  "App.model.admin.ConsentLetters": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "App.view.admin.NewAppointmentWindow": [
    "widget.newappointmentwindow"
  ],
  "App.Application": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "App.model.admin.PatientDemographics": [],
  "Ext.ux.DataView.DragSelector": [],
  "App.model.admin.Batches": [],
  "App.view.PatientArea": [
    "widget.patientarea"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.upload.ItemGridPanel": [],
  "Ext.ux.upload.Item": [],
  "App.store.admin.IPAccess": [],
  "App.model.admin.Users": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "App.view.patient.Insurance": [
    "widget.insurance"
  ],
  "App.view.ux.ActivityMonitor": [],
  "App.view.admin.ConsentLetterDetails": [
    "widget.consentletterdetails"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "App.view.patient.InsuranceCard": [
    "widget.insurancecard"
  ],
  "App.view.logon.Window": [
    "widget.logon"
  ],
  "App.view.admin.ConsentLetters": [
    "widget.consentgrid"
  ],
  "App.model.admin.Templates": [],
  "App.view.patient.Demographics": [
    "widget.demographics"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.upload.BrowseButton": [],
  "Ext.ux.upload.uploader.AbstractUploader": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "App.controller.Forms": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "App.store.admin.Templates": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.upload.uploader.DummyUploader": [],
  "App.view.patient.Calendar": [
    "widget.patientcalendar"
  ],
  "ExtThemeNeptune.panel.Table": [],
  "Ext.ux.upload.uploader.FormDataUploader": [],
  "App.view.admin.CMS": [
    "widget.cmsgrid"
  ],
  "App.view.Viewport": [
    "widget.appview"
  ],
  "Ext.ux.event.Recorder": [],
  "App.controller.Navigation": [],
  "App.view.fields.PatientSearch": [
    "widget.patientsearch"
  ],
  "App.view.admin.AppointmentCalendar": [
    "widget.appointmentcalendar"
  ],
  "App.view.fields.AppointmentBooks": [
    "widget.appointmentbookscombo"
  ],
  "App.model.admin.GeoIps": [],
  "App.model.admin.InsuranceCombo": [],
  "App.store.admin.PatientDemographics": [],
  "Ext.ux.ajax.SimManager": [],
  "App.store.admin.AppointmentBooks": [],
  "App.view.admin.Users": [
    "widget.users"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "App.view.admin.Plugins": [
    "widget.pluginspanel"
  ],
  "App.view.ux.WebCamWindow": [
    "widget.webcamwindow"
  ],
  "App.view.admin.CMSDetails": [
    "widget.cmsdetails"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "App.controller.Main": [],
  "App.model.admin.Documents": [],
  "App.model.calendar.PatientSearch": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "App.store.calendar.PatientSearch": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.upload.Panel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "App.view.admin.Reports": [
    "widget.reports"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "App.view.patient.ConsentLetters": [
    "widget.consentletters"
  ],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "App.store.admin.CMS": [],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "App.model.admin.PatientInsurance": [],
  "App.store.admin.Appointments": [],
  "App.controller.Abstract": [],
  "Ext.ux.upload.uploader.ExtJsUploader": [],
  "Ext.ux.upload.Manager": [],
  "App.model.admin.Referring": [],
  "Ext.ux.FieldReplicator": [],
  "App.model.admin.Sessions": [],
  "App.model.admin.PatientClinical": [],
  "ExtThemeNeptune.panel.Panel": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "App.view.admin.Administrative": [
    "widget.administrative"
  ],
  "App.store.admin.ConsentSignatures": [],
  "App.controller.Calendar": [],
  "App.store.admin.PatientInsurance": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "App.model.admin.CMS": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "App.view.ux.RelationsCombo": [
    "widget.relationfield"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.upload.uploader.AbstractXhrUploader": [],
  "App.view.logon.PatientForm": [
    "widget.logonpatientform"
  ],
  "App.store.admin.ConsentLetters": [],
  "App.model.admin.Confirmations": [],
  "App.view.fields.DateTime": [
    "widget.datetimefield"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "App.controller.Plugins": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "App.view.AdminArea": [
    "widget.adminarea"
  ],
  "App.store.admin.Users": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "App.store.admin.Logs": [],
  "Ext.ux.upload.data.Connection": [],
  "App.view.Request": [
    "widget.request"
  ],
  "App.store.WebCamCameras": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "ExtThemeNeptune.layout.component.Dock": [],
  "App.controller.WebCam": [],
  "App.model.admin.Appointments": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "App.view.ux.NavigationTabs": [
    "widget.navigationtabs"
  ],
  "Ext.ux.event.Player": [],
  "App.view.admin.AppointmentBooks": [
    "widget.appointmentbooks"
  ],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "App.view.ux.StateCombo": [
    "widget.statefield"
  ],
  "App.view.ux.SexCombo": [
    "widget.sexfield"
  ],
  "Ext.ux.event.Maker": [],
  "Ext.ux.upload.StatusBar": [],
  "Ext.ux.DataView.Draggable": [],
  "App.model.admin.ConsentSignatures": [],
  "App.store.admin.PatientClinical": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "App.view.admin.Logs": [
    "widget.logs"
  ],
  "Ext.ux.upload.Dialog": [],
  "App.controller.Admin": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "App.model.admin.AppointmentBooks": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "App.view.patient.ThankYou": [
    "widget.thankyou"
  ],
  "Ext.ux.upload.Queue": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "ExtThemeNeptune.Component": [],
  "App.model.admin.FacultyCombo": [],
  "App.model.admin.IPAccess": [],
  "App.model.admin.Logs": [],
  "App.model.admin.Plugins": []
});
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/Component.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Panel.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/picker/Month.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Table.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/menu/Menu.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/menu/Separator.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Tool.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/tab/Tab.js");
