/**
 * Created with IntelliJ IDEA.
 * User: ernesto
 * Date: 4/4/13
 * Time: 4:30 PM
 * To change this template use File | Settings | File Templates.
 */
Ext.define('App.model.admin.PatientClinical',{
	extend:'Ext.data.Model',
	table:{
		name:'patient_clinical',
		comment:'patients clinical history data'
	},
	fields:[
		{
			name:'id',
			type:'int'
		},
		{
			name:'pid',
			type:'int'
		},
		{
			name:'carAccident',
			type:'bool'
		},
		{
			name:'workAccident',
			type:'bool'
		},
		{
			name:'otherAccident',
			type:'bool'
		},
		{
			name:'lastMedicalExam',
			type:'date',
			dataType:'date',
			dateFormat:'Y-m-d'
		},
		{
			name:'isUnderTreatment',
			type:'bool'
		},
		{
			name:'isUnderTreatmentNote',
			type:'string'
		},
		{
			name:'hasBeenHospitalized',
			type:'bool'
		},
		{
			name:'hasBeenHospitalizedNote',
			type:'string'
		},
		{
			name:'isAllergic',
			type:'bool'
		},
		{
			name:'isAllergicNote',
			type:'string'
		},
		{
			name:'isPregnant',
			type:'bool'
		},
		{
			name:'isPregnantNote',
			type:'string'
		},
		{
			name:'hasSufferOf',
			type:'array',
			comment:'Array de Padecimientos'
		},
		{
			name:'hasSufferOfOther',
			type:'string'
		},
		{
			name:'Drug1',
			type:'string',
			len:100
		},
		{
			name:'Drug2',
			type:'string',
			len:100
		},
		{
			name:'Drug3',
			type:'string',
			len:100
		},
		{
			name:'Drug4',
			type:'string',
			len:100
		},
		{
			name:'Drug5',
			type:'string',
			len:100
		},
		{
			name:'Drug6',
			type:'string',
			len:100
		},
		{
			name:'Drug7',
			type:'string',
			len:100
		},
		{
			name:'Drug8',
			type:'string',
			len:100
		},
		{
			name:'Drug9',
			type:'string',
			len:100
		},
		{
			name:'Drug10',
			type:'string',
			len:100
		},
		{
			name:'Drug11',
			type:'string',
			len:100
		},
		{
			name:'Drug12',
			type:'string',
			len:100
		},
		{
			name:'Drug13',
			type:'string',
			len:100
		},
		{
			name:'Drug14',
			type:'string',
			len:100
		},
		{
			name:'Drug15',
			type:'string',
			len:100
		},
		{
			name:'isSmoker',
			type:'bool'
		},
		{
			name:'isDrinker',
			type:'bool'
		},
		{
			name:'isDrugUser',
			type:'bool'
		},
		{
			name:'famHistory',
			type:'array',
			comment:'Array de Historial Familiar',
			len:500
		},
		{
			name:'famHistoryWhoDiabetes',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoGlaucoma',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoHypertension',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoAsthma',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoStroke',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoTuberculosis',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoCancer',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoBronchialAsthma',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoHaematologicalDisorders',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoHeartAttack',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoHeartMurmur',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoSeizures',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoOtitisMedia',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoOverweight',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoSexualTransmission',
			type:'string'
		},
		{
			name:'famHistoryWhoHighCholesterol',
			type:'string',
			len:100
		},
		{
			name:'famHistoryWhoToroidDisease',
			type:'string',
			len:100
		},
		{
			name:'famHistoryOthers',
			type:'string',
			len:500
		},
		{
			name:'hasReceivedPTThisYear',
			type:'bool'
		},
		{
			name:'hasReceivedPTThisYearTreatment',
			type:'string'
		},
		{
			name:'hasReceivedPTThisYearWhere',
			type:'string'
		},
		{
			name:'hasReceivedPTThisYearHowMany',
			type:'int'
		},
		{
			name:'hasReceivedPTPastYear',
			type:'bool'
		},
		{
			name:'hasReceivedPTPastYearTreatment',
			type:'string'
		},
		{
			name:'hasReceivedPTPastYearWhere',
			type:'string'
		},
		{
			name:'hasReceivedPTPastYearHowMany',
			type:'int'
		},
        {
            name:'synced',
            type:'bool',
            defaultValue:0,
            comment:'0 = dirty / not synced'
        },
        {
            name:'lastUpdate',
            type:'date',
            dataType:'TIMESTAMP'
        }
	],
	associations: [
		{
			type: 'belongsTo',
			model: 'App.model.admin.PatientDemographics',
			foreignKey: 'pid',
			setterName:'setPatientDemographics',
			getterName:'getPatientDemographics'
		}
	],
	proxy:{
		type:'direct',
		api:{
			read:Patients.getPatientClinical,
			create:Patients.addPatientClinical,
			update:Patients.updatePatientClinical
		}
	}
});